# Project Specific
version=1.0.0
group=com.nyfaria
mod_name=Combat Oddities
mod_author=Nyfaria, AJ
mod_id=combat_oddities
description=Random Odd Weapons and (Eventually) Other things.
credits=
curseforge_publishing_enabled=true
curseforge_project_id=1712084
modrinth_publishing_enabled=false
modrinth_project_id=OFC0es59
dry_run=false

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Common
minecraft_version=1.21.1
java_version=21
license=ARR
